name: Trigger auto deployment for ava-test-crm-poc

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ava-test-crm-poc-AutoDeployTrigger-e8ffb4fb-799e-41a3-a813-c154423c751c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AVATESTCRMPOC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AVATESTCRMPOC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AVATESTCRMPOC_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.AVATESTCRMPOC_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AVATESTCRMPOC_REGISTRY_PASSWORD }}
          containerAppName: ava-test-crm-poc
          resourceGroup: AvaTestCRMPOC
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


